INSERT OR IGNORE INTO launches (
  id,
  scenario_draft_id,
  name,
  mode,
  audience,
  status,
  starts_at,
  participants_label,
  scenario_brief,
  learning_objectives,
  tabletop_phase,
  facilitator_notes,
  report_closeout_notes,
  report_follow_up_text,
  report_closed_at,
  report_closed_by_user_id,
  report_closed_by_name,
  created_at,
  updated_at
) VALUES
  (
    'launch_q2_cyber_wave1',
    'draft_q2_cyber',
    'Q2 Cyber Escalation Drill',
    'individual',
    'Operations + Compliance',
    'in_progress',
    '2026-03-21',
    '2 assignees',
    'A critical identity provider begins failing across employee authentication and advisor portal access. Participants must decide the first escalation, assess customer impact, and coordinate the internal response using approved procedures.',
    'Validate the first escalation actions, vendor coordination path, and cross-functional communication chain.',
    NULL,
    '',
    '',
    '',
    NULL,
    NULL,
    NULL,
    '2026-03-06T18:00:00.000Z',
    '2026-03-18T14:30:00.000Z'
  ),
  (
    'launch_vendor_tabletop_exec',
    'draft_vendor_tabletop',
    'Core Vendor Outage Tabletop',
    'tabletop',
    'Executive Team',
    'scheduled',
    '2026-03-27',
    '2 leaders',
    'A primary operations vendor loses regional processing capacity during market hours. The executive team must confirm the first decision path, assign external communications ownership, and determine whether continuity workarounds are sufficient.',
    'Pressure test executive decision rights, external communications ownership, and continuity workaround readiness.',
    'briefing',
    'Start with the vendor outage alert, then press on customer communications, manual workarounds, and escalation ownership.',
    '',
    '',
    NULL,
    NULL,
    NULL,
    '2026-03-08T18:00:00.000Z',
    '2026-03-08T18:00:00.000Z'
  ),
  (
    'launch_vendor_tabletop_q1_review',
    'draft_vendor_tabletop',
    'Executive Vendor Outage Tabletop - Q1 Review',
    'tabletop',
    'Executive Team',
    'completed',
    '2026-03-05',
    '2 leaders',
    'Leadership reviewed a quarter-end vendor disruption exercise focused on failover authority, customer communications, and whether manual continuity workarounds could be sustained through market close.',
    'Confirm executive decision rights, manual-workaround thresholds, and who owns external communications when a core vendor disruption extends past the first operating window.',
    'after_action',
    'Leadership aligned quickly once the communications owner was named, but the trigger for escalating from manual workaround to broader client communication remained too loose.',
    'Executive ownership became clear once the communications lead was named. The team still needs a firmer trigger for moving from manual workaround mode into external communications and board-level escalation.',
    'Publish a one-page executive decision checklist for critical vendor outages.\nDocument the trigger for moving from manual workarounds to external client communications.',
    '2026-03-10T16:30:00.000Z',
    'user_dana_admin',
    'Dana Smith',
    '2026-03-05T14:00:00.000Z',
    '2026-03-10T16:30:00.000Z'
  );

UPDATE launches
SET status = 'in_progress',
    starts_at = '2026-03-18',
    participants_label = '2 assignees',
    scenario_brief = 'A critical identity provider begins failing across employee authentication and advisor portal access. Participants must decide the first escalation, assess customer impact, and coordinate the internal response using approved procedures.',
    learning_objectives = 'Validate the first escalation actions, vendor coordination path, and cross-functional communication chain.',
    tabletop_phase = NULL,
    facilitator_notes = '',
    report_closeout_notes = '',
    report_follow_up_text = '',
    report_closed_at = NULL,
    report_closed_by_user_id = NULL,
    report_closed_by_name = NULL,
    updated_at = '2026-03-18T14:30:00.000Z'
WHERE id = 'launch_q2_cyber_wave1';

UPDATE launches
SET status = 'scheduled',
    starts_at = '2026-03-27',
    participants_label = '2 leaders',
    tabletop_phase = 'briefing',
    facilitator_notes = 'Start with the vendor outage alert, then press on customer communications, manual workarounds, and escalation ownership.',
    updated_at = '2026-03-08T18:00:00.000Z'
WHERE id = 'launch_vendor_tabletop_exec';

INSERT OR IGNORE INTO participant_runs (
  id,
  launch_id,
  roster_member_id,
  participant_name,
  participant_email,
  participant_role,
  participant_team,
  status,
  first_action,
  escalation_choice,
  impact_assessment,
  notes,
  policy_acknowledged,
  score_percent,
  required_actions_completed,
  total_required_actions,
  due_at,
  started_at,
  submitted_at,
  created_at,
  updated_at
) VALUES
  (
    'run_kim_ops',
    'launch_q2_cyber_wave1',
    'roster_kim_patel',
    'Kim Patel',
    'kim.patel@altira-demo.com',
    'Operations Manager',
    'Operations',
    'submitted',
    'Escalate to the incident commander and confirm the identity provider outage scope.',
    'Incident Commander',
    'Advisor and employee login failures interrupt transaction review, but customer assets remain accessible.',
    'The vendor contact tree needs a cleaner handoff between security and operations.',
    1,
    100,
    4,
    4,
    '2026-03-21',
    '2026-03-18T13:45:00.000Z',
    '2026-03-18T14:30:00.000Z',
    '2026-03-18T13:45:00.000Z',
    '2026-03-18T14:30:00.000Z'
  ),
  (
    'run_jordan_compliance',
    'launch_q2_cyber_wave1',
    'roster_jordan_lee',
    'Jordan Lee',
    'jordan.lee@altira-demo.com',
    'Compliance Officer',
    'Compliance',
    'assigned',
    '',
    '',
    '',
    '',
    0,
    NULL,
    0,
    4,
    '2026-03-18',
    NULL,
    NULL,
    '2026-03-18T09:00:00.000Z',
    '2026-03-18T09:00:00.000Z'
  ),
  (
    'run_vendor_exec_coo',
    'launch_vendor_tabletop_exec',
    'roster_morgan_avery',
    'Morgan Avery',
    'morgan.avery@altira-demo.com',
    'Chief Operating Officer',
    'Executive',
    'assigned',
    '',
    '',
    '',
    '',
    0,
    NULL,
    0,
    4,
    '2026-03-27',
    NULL,
    NULL,
    '2026-03-08T18:00:00.000Z',
    '2026-03-08T18:00:00.000Z'
  ),
  (
    'run_vendor_exec_ciso',
    'launch_vendor_tabletop_exec',
    'roster_taylor_brooks',
    'Taylor Brooks',
    'taylor.brooks@altira-demo.com',
    'Chief Information Security Officer',
    'Security',
    'assigned',
    '',
    '',
    '',
    '',
    0,
    NULL,
    0,
    4,
    '2026-03-27',
    NULL,
    NULL,
    '2026-03-08T18:00:00.000Z',
    '2026-03-08T18:00:00.000Z'
  ),
  (
    'run_vendor_review_coo',
    'launch_vendor_tabletop_q1_review',
    'roster_morgan_avery',
    'Morgan Avery',
    'morgan.avery@altira-demo.com',
    'Chief Operating Officer',
    'Executive',
    'submitted',
    'Confirm whether vendor failover authority remains with operations or requires executive approval before customer impact widens.',
    'Executive Sponsor',
    'Regional processing slowdown can be held manually for one window, but customer communications ownership becomes time-critical if the outage extends.',
    'The team aligned quickly after naming the communications owner, but the trigger for broader customer updates needs to be codified.',
    1,
    92,
    4,
    4,
    '2026-03-05',
    '2026-03-05T15:00:00.000Z',
    '2026-03-05T15:45:00.000Z',
    '2026-03-05T15:00:00.000Z',
    '2026-03-05T15:45:00.000Z'
  ),
  (
    'run_vendor_review_ciso',
    'launch_vendor_tabletop_q1_review',
    'roster_taylor_brooks',
    'Taylor Brooks',
    'taylor.brooks@altira-demo.com',
    'Chief Information Security Officer',
    'Security',
    'submitted',
    'Confirm that the outage is operational rather than malicious, then hand off the customer-impact threshold to the executive team.',
    'Executive Sponsor',
    'No malicious activity is present, but the extended vendor outage would force manual workarounds and time-sensitive client messaging.',
    'Security ownership was clear, but the move from internal outage management to external communications still needs a firmer trigger.',
    1,
    84,
    4,
    4,
    '2026-03-05',
    '2026-03-05T15:05:00.000Z',
    '2026-03-05T15:50:00.000Z',
    '2026-03-05T15:05:00.000Z',
    '2026-03-05T15:50:00.000Z'
  );

UPDATE participant_runs
SET roster_member_id = 'roster_kim_patel',
    participant_email = 'kim.patel@altira-demo.com',
    participant_team = 'Operations',
    status = 'submitted',
    first_action = 'Escalate to the incident commander and confirm the identity provider outage scope.',
    escalation_choice = 'Incident Commander',
    impact_assessment = 'Advisor and employee login failures interrupt transaction review, but customer assets remain accessible.',
    notes = 'The vendor contact tree needs a cleaner handoff between security and operations.',
    policy_acknowledged = 1,
    score_percent = 100,
    required_actions_completed = 4,
    total_required_actions = 4,
    due_at = '2026-03-21',
    started_at = '2026-03-18T13:45:00.000Z',
    submitted_at = '2026-03-18T14:30:00.000Z',
    updated_at = '2026-03-18T14:30:00.000Z'
WHERE id = 'run_kim_ops';

UPDATE participant_runs
SET roster_member_id = 'roster_jordan_lee',
    participant_email = 'jordan.lee@altira-demo.com',
    participant_team = 'Compliance',
    status = 'assigned',
    first_action = '',
    escalation_choice = '',
    impact_assessment = '',
    notes = '',
    policy_acknowledged = 0,
    score_percent = NULL,
    required_actions_completed = 0,
    total_required_actions = 4,
    due_at = '2026-03-21',
    started_at = NULL,
    submitted_at = NULL,
    updated_at = '2026-03-18T09:00:00.000Z'
WHERE id = 'run_jordan_compliance';

UPDATE participant_runs
SET roster_member_id = 'roster_morgan_avery',
    participant_email = 'morgan.avery@altira-demo.com',
    participant_team = 'Executive',
    due_at = '2026-03-27'
WHERE id = 'run_vendor_exec_coo';

UPDATE participant_runs
SET roster_member_id = 'roster_taylor_brooks',
    participant_email = 'taylor.brooks@altira-demo.com',
    participant_team = 'Security',
    due_at = '2026-03-27'
WHERE id = 'run_vendor_exec_ciso';

INSERT OR IGNORE INTO audit_events (
  id,
  category,
  action,
  target_type,
  target_id,
  actor_user_id,
  actor_name,
  actor_role,
  summary,
  detail,
  created_at
) VALUES
  (
    'audit_operations_submission_kim_q2',
    'operations',
    'participant_run_submitted',
    'participant_run',
    'run_kim_ops',
    'user_dana_admin',
    'Dana Smith',
    'admin',
    'Kim Patel submitted evidence for Q2 Cyber Escalation Drill.',
    'Operations response scored 100% and highlighted a vendor handoff gap between security and operations.',
    '2026-03-18T14:30:00.000Z'
  ),
  (
    'audit_operations_vendor_closeout',
    'operations',
    'launch_updated',
    'launch',
    'launch_vendor_tabletop_q1_review',
    'user_dana_admin',
    'Dana Smith',
    'admin',
    'Dana Smith closed the evidence package for Executive Vendor Outage Tabletop - Q1 Review.',
    'Closeout captured leadership gaps, follow-up actions, and an approved after-action package.',
    '2026-03-10T16:30:00.000Z'
  );
